spring:
  main:
    banner-mode: off
    log-startup-info: false
  profiles:
    active: ${EXEC_ENV:prod}
  webflux:
    base-path: /client/api
  application:
    name: client-service
#
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: 27900

#