spring:
  main:
    banner-mode: off
    log-startup-info: false
  profiles:
    active: ${EXEC_ENV:prod}
  webflux:
    base-path: /client/api
  application:
    name: client-service
  rabbitmq:
    rabbitmq:
      host: ${MQ_HOST:rabbit_mq}
      port: ${MQ_PORT:5672}
      username: ${MQ_USER:guest}
      password: ${MQ_PASSWORD:guest}
#
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: 27900

#