spring:
  main:
    banner-mode: off
    log-startup-info: false
  webflux:
    base-path: /client/api
  profiles:
    active: ${EXEC_ENV:test}
#
eureka:
  client:
    enabled: false

server:
  port: 27900
  servlet:
    context-path: /client/api

#