spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:jenzi}
    password: ${DB_PASSWORD:jenzi@2022}
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:jenzi}