spring:
  main:
    banner-mode: off
    log-startup-info: false
  profiles:
    active: ${EXEC_ENV:prod}
  webflux:
    base-path: /client/api
#
eureka:
  client:
    enabled: false

server:
  port: 27900

#